import base64
import binascii
from pathlib import Path
from typing import Any

import cv2
import numpy as np
from fastapi import HTTPException
from ultralytics import YOLO


# Path to the wildfire model supplied in the skeleton folder.
# This model is correct for the assignment only if the allocated model is
# "Wildfire & Smoke Detection" based on the student ID ending digit.
MODEL_PATH = Path("fire-models/fire_m.pt")

# Load the model once when the server starts.
# This avoids the expensive cost of reloading YOLO for every API request.
model = YOLO(str(MODEL_PATH))


def decode_base64_image(image_base64: str) -> np.ndarray:
    """
    Convert a base64 image string into an OpenCV image.

    The API receives JSON, so the image comes as text.
    This function decodes that text back into image pixels.
    """
    try:
        # Some clients may send a data URL such as
        # "data:image/jpeg;base64,..."; only the encoded image is needed.
        if "," in image_base64:
            image_base64 = image_base64.split(",", 1)[1]

        # Decode base64 text into bytes, convert those bytes into a NumPy
        # buffer, then let OpenCV reconstruct the image matrix.
        image_bytes = base64.b64decode(image_base64, validate=True)
        image_array = np.frombuffer(image_bytes, dtype=np.uint8)
        image = cv2.imdecode(image_array, cv2.IMREAD_COLOR)

        # cv2.imdecode returns None when the bytes are valid base64 but do not
        # represent a valid image file.
        if image is None:
            raise ValueError("Could not decode image.")

        return image

    except (binascii.Error, ValueError) as exc:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid base64 image: {str(exc)}"
        )


def encode_image_to_base64(image: np.ndarray) -> str:
    """
    Convert an OpenCV image into a base64 JPEG string.
    This is used by /api/annotate.
    """
    # Encode the annotated OpenCV image as JPEG before sending it in JSON.
    success, buffer = cv2.imencode(".jpg", image)

    if not success:
        raise HTTPException(
            status_code=500,
            detail="Failed to encode annotated image."
        )

    return base64.b64encode(buffer).decode("utf-8")


def run_yolo_prediction(uuid: str, image_base64: str) -> dict[str, Any]:
    """
    Run YOLO detection and return the required JSON response format.
    """
    # The assignment request payload contains a base64 string, but YOLO expects
    # an image array, so decoding must happen before inference.
    image = decode_base64_image(image_base64)

    # Run YOLO inference. Ultralytics also records preprocess, inference, and
    # postprocess timing in the result object.
    results = model.predict(image, verbose=False)

    # We send one image, so we use the first result.
    result = results[0]

    detections = []
    boxes = []

    if result.boxes is not None:
        for box in result.boxes:
            # YOLO returns bounding boxes as x1, y1, x2, y2. The assignment
            # response format requires x, y, width, and height.
            x1, y1, x2, y2 = box.xyxy[0].tolist()

            confidence = float(box.conf[0])
            class_id = int(box.cls[0])
            class_name = result.names[class_id]

            # Store the class label separately from the matching bounding box,
            # following the required /api/predict payload structure.
            detections.append(class_name)

            boxes.append({
                "x": int(x1),
                "y": int(y1),
                "width": int(x2 - x1),
                "height": int(y2 - y1),
                "probability": round(confidence, 4)
            })

    # These latency values are required by the assignment and are generated by
    # the Ultralytics prediction call.
    speed = result.speed

    return {
        "uuid": uuid,
        "count": len(detections),
        "detections": detections,
        "boxes": boxes,
        "speed_preprocess_ms": round(float(speed.get("preprocess", 0)), 2),
        "speed_inference_ms": round(float(speed.get("inference", 0)), 2),
        "speed_postprocess_ms": round(float(speed.get("postprocess", 0)), 2)
    }


def run_yolo_annotation(uuid: str, image_base64: str) -> dict[str, Any]:
    """
    Run YOLO detection and return an annotated image as base64.
    """
    # Decode the incoming JSON image string before passing it to the model.
    image = decode_base64_image(image_base64)

    results = model.predict(image, verbose=False)
    result = results[0]

    # Ultralytics draws boxes and labels on the image.
    annotated_image = result.plot()

    # The annotated image must be returned as text because JSON cannot carry
    # raw binary image data directly.
    annotated_base64 = encode_image_to_base64(annotated_image)

    return {
        "uuid": uuid,
        "image": annotated_base64
    }
