"""
FILE: app/schemas.py
ROLE: Defines the exact shape of every JSON request and response using Pydantic.
      FastAPI uses these classes to automatically validate and parse data.

CALLED FROM: app/main.py
  - PredictionRequest  → used as the type hint for the 'request' parameter in
                         both predict() and annotate() routes. FastAPI reads this
                         class to know what fields to expect in the incoming JSON.
  - PredictResponse    → used as response_model= in @app.post("/api/predict").
                         FastAPI validates the dict returned by the route against
                         this schema before sending it to the client.
  - AnnotateResponse   → used as response_model= in @app.post("/api/annotate").

HOW VALIDATION WORKS:
  When a client sends POST /api/predict with JSON body, FastAPI:
    1. Reads the Content-Type: application/json header
    2. Parses the body as JSON
    3. Feeds the parsed dict into PredictionRequest(**data)
    4. If any field is missing or wrong type → HTTP 422 Unprocessable Entity
    5. If valid → the route function receives a PredictionRequest object

ASSIGNMENT SPEC MAPPING:
  Request  = { "uuid": "...", "image": "base64string..." }
  Response = { "uuid", "count", "detections", "boxes", "speed_*_ms" }
"""

from pydantic import BaseModel, Field
from typing import List


class PredictionRequest(BaseModel):
    """
    The JSON body that clients (Locust, test scripts, Postman) send to both
    /api/predict and /api/annotate.

    Fields:
      uuid  — a unique string ID (usually a UUID4) the client generates per request.
               Echoed back in the response so async clients can match request→response.
      image — the image encoded as a Base64 ASCII string.
               JSON cannot carry raw binary, so the client converts:
               JPEG/PNG bytes → base64.b64encode() → ASCII string → JSON field.
    """
    uuid:  str = Field(..., description="Unique request ID generated by the client")
    image: str = Field(..., description="Base64-encoded image (JPEG or PNG)")
    # Field(...) means the field is REQUIRED — Pydantic raises ValidationError if missing
    # The description populates the Swagger UI at /docs


class BoxResponse(BaseModel):
    """
    One bounding box for a single detected object.
    Coordinates are in pixels relative to the top-left corner of the image.

    x, y      = top-left corner of the bounding box
    width     = horizontal span (pixels)
    height    = vertical span (pixels)
    probability = confidence score from YOLO (0.0 to 1.0)

    YOLO internally stores boxes as (x1,y1,x2,y2) corner format.
    predictor.py converts to this (x,y,width,height) format because
    the assignment spec requires it — and it is more natural for rendering.
    """
    x:           float
    y:           float
    width:       float
    height:      float
    probability: float


class PredictResponse(BaseModel):
    """
    The JSON body returned by /api/predict.
    Maps directly to the Required Response Payload in the assignment spec.

    Fields:
      uuid                 — echoed from the request so the client can correlate
      count                — number of objects detected (0 if nothing found)
      detections           — list of class name strings e.g. ["fire", "smoke"]
      boxes                — list of BoxResponse objects, one per detection
      speed_preprocess_ms  — time YOLO spent resizing/normalising the image
      speed_inference_ms   — time YOLO spent running the neural network forward pass
      speed_postprocess_ms — time YOLO spent converting raw tensor outputs to boxes
    """
    uuid:                 str
    count:                int
    detections:           List[str]         # e.g. ["fire", "smoke", "smoke"]
    boxes:                List[BoxResponse]  # same length as detections
    speed_preprocess_ms:  float
    speed_inference_ms:   float
    speed_postprocess_ms: float


class AnnotateResponse(BaseModel):
    """
    The JSON body returned by /api/annotate.
    Contains the original image with bounding boxes and labels drawn on it,
    re-encoded as a Base64 string so it can travel inside JSON.

    Fields:
      uuid            — echoed from the request
      annotated_image — the rendered image as a Base64 string (JPEG format)
                        Client decodes this with base64.b64decode() to get the image file.
    """
    uuid:            str
    annotated_image: str   # base64-encoded JPEG with boxes drawn by result.plot()
